import assert from 'node:assert/strict';
import {Client} from './client.mjs';
const alex=await new Client().login('alex'),casey=await new Client().login('casey'),jordan=await new Client().login('jordan'),morgan=await new Client().login('morgan');
const hr=await new Client().login('taylor'),hrLead=await new Client().login('riley'),coordinator=await new Client().login('sam'),ceo=await new Client().login('avery');
assert.deepEqual(casey.user.workspaces.map(w=>w.key),['employee','manager']);
assert.deepEqual(hr.user.workspaces.map(w=>w.key),['employee','hr']);
assert.deepEqual(ceo.user.workspaces.map(w=>w.key),['executive']);
await alex.call('workspace&scope=hr',null,403);
await alex.call('dashboard',null,403);
await ceo.call('workspace&scope=employee',null,403);
let own=(await alex.call('workspace&scope=employee')).data;
assert.equal(own.plans.length,1);assert.equal(own.pips.length,0);
const itemId=own.plans[0].actions[0].id;
const getItem=async client=>(await client.call(`work_item&type=pdp_action&id=${itemId}`)).item;
let item=await getItem(alex);
assert.equal(item.progress.completed,1);assert.equal(item.progress.blocked,true);assert.equal(item.progress.overdue,true);
await jordan.call(`work_item&type=pdp_action&id=${itemId}`,null,404);
await hrLead.call(`work_item&type=pdp_action&id=${itemId}`,null,404);
await getItem(casey);
let step=item.steps[0];
await alex.call('set_step_status',{id:step.id,status:'invalid'},422);
await alex.call('set_step_status',{id:step.id,status:'completed'},403,false);
await jordan.call('set_step_status',{id:step.id,status:'completed'},404);
await alex.call('update_work_step',{id:step.id,title:'Unauthorized redefinition'},403);
await alex.call('add_work_step',{type:'pdp_action',workId:itemId,title:'Unauthorized step'},403);
for(const status of ['not_started','in_progress','blocked','completed']) {
  step=(await getItem(alex)).steps[0];
  await alex.call('set_step_status',{id:step.id,version:step.version,status,note:`Testing ${status}`});
  const saved=(await getItem(casey)).steps[0];
  assert.equal(saved.status,status);assert.equal(saved.note,`Testing ${status}`);assert.equal(saved.completed,status==='completed');
  assert.equal(saved.completedAt!==null,status==='completed');
  await alex.call('set_step_status',{id:step.id,version:step.version,status:'not_started'},409);
}
step=(await getItem(alex)).steps[0];
await alex.call('set_step_status',{id:step.id,version:step.version,status:'completed',note:'Edited completion note'});
assert.equal((await getItem(alex)).steps[0].completedAt,step.completedAt);
for(const s of (await getItem(alex)).steps)await alex.call('set_step_status',{id:s.id,version:s.version,status:'completed'});
item=await getItem(alex);assert.equal(item.progress.percent,100);assert.equal(item.status,'completed');assert.equal(item.progress.overdue,false);
own=(await alex.call('workspace&scope=employee')).data;assert.equal(own.plans[0].status,'completed');assert.equal(own.plans[0].progress.status,'completed');
step=item.steps[0];await alex.call('set_step_status',{id:step.id,version:step.version,status:'in_progress'});
own=(await alex.call('workspace&scope=employee')).data;assert.equal(own.plans[0].status,'agreed');assert.equal(own.plans[0].progress.completed,3);
const team=(await casey.call('dashboard')).pdps.find(p=>p.id===itemId);assert.equal(team.steps.filter(s=>s.completed).length,3);
const ancestor=(await jordan.call('dashboard'));assert(!ancestor.pdps.some(p=>p.id===itemId));
const hrPlans=(await hr.call('workspace&scope=hr')).data.pips;assert.equal(hrPlans.length,1);
assert.equal((await hrLead.call('workspace&scope=hr')).data.pips.length,0);
assert.equal((await coordinator.call('workspace&scope=hr')).data.pips.length,0);
const objective=hrPlans[0].objectives[0];
await hrLead.call(`work_item&type=pip_objective&id=${objective.id}`,null,404);
await hr.call('set_step_status',{id:objective.steps[1].id,version:objective.steps[1].version,status:'blocked',note:'Review together at next check-in.'});
await casey.call('update_pip_status',{id:Number(hrPlans[0].id),status:'closed',note:'Closed for the automated test.'});
await hr.call('set_step_status',{id:objective.steps[0].id,status:'not_started'},409);
const privateReview=own.reviews[0];assert.equal(privateReview.final_rating,null);assert.equal(privateReview.manager_summary,null);assert.deepEqual(privateReview.feedback,[]);
const released=(await morgan.call('workspace&scope=employee')).data.reviews[0];assert.equal(released.feedback.length,3);assert(!JSON.stringify(released.feedback).includes('respondent'));
const formRequest=own.requests.find(r=>r.type==='self');
await hr.call(`feedback_form&id=${formRequest.id}`,null,404);
const form=await alex.call(`feedback_form&id=${formRequest.id}`);
await alex.call('submit_personal_feedback',{id:formRequest.id,ratings:[]},422);
await alex.call('submit_personal_feedback',{id:formRequest.id,ratings:form.competencies.map(c=>({competencyId:Number(c.id),score:4,comment:'An illustrative self review.'}))});
await alex.call('submit_personal_feedback',{id:formRequest.id,ratings:[]},409);
assert.equal((await alex.call('workspace&scope=employee')).data.reviews[0].status,'self_submitted');
const newGoal=await alex.call('create_pdp',{employeeId:Number(alex.user.id),title:'Practice a new skill',description:'Use a practical example',due:'2099-12-31',steps:['Prepare','Practice']});
assert.equal((await alex.call(`work_item&type=pdp_action&id=${newGoal.id}`)).item.canEdit,true);
let editable=(await alex.call(`work_item&type=pdp_action&id=${newGoal.id}`)).item;
await alex.call('update_work_step',{id:editable.steps[0].id,title:'Prepare an example'});
assert.equal((await alex.call(`work_item&type=pdp_action&id=${newGoal.id}`)).item.steps[0].title,'Prepare an example');
const added=await alex.call('add_work_step',{type:'pdp_action',workId:newGoal.id,title:'Reflect'});
await alex.call('delete_work_step',{id:added.id});
assert.equal((await alex.call(`work_item&type=pdp_action&id=${newGoal.id}`)).item.steps.length,2);
await alex.call('create_pdp',{employeeId:Number(casey.user.id),title:'Invalid assignment',description:'No access',due:'2099-12-31',steps:['Test']},403);
await ceo.call('create_pdp',{employeeId:Number(ceo.user.id),title:'Unavailable personal plan',description:'No employee workspace',due:'2099-12-31',steps:['Test']},403);
console.log('PASS: workspace boundaries, all step transitions, timestamps, notes, conflicts, CSRF, plan aggregation, cross-session reads, HR ownership, anonymous/released results, feedback submission and creation.');
