import assert from 'node:assert/strict';
import {Client} from './client.mjs';
const alex=await new Client().login('alex'),casey=await new Client().login('casey');
const drew=await new Client().login('drew'),blair=await new Client().login('blair');
const jamie=await new Client().login('jamie'),jordan=await new Client().login('jordan');
const riley=await new Client().login('riley'),taylor=await new Client().login('taylor');
let personal=(await alex.call('workspace&scope=employee')).data;
const review=personal.reviews.find(r=>r.cycle_status==='open');
const candidates=(await alex.call(`peer_candidates&participantId=${review.id}`)).candidates;
assert(!candidates.some(p=>Number(p.id)===Number(alex.user.id)||Number(p.id)===Number(casey.user.id)));
await drew.call(`peer_candidates&participantId=${review.id}`,null,404);
await alex.call('nominate_peer',{participantId:review.id,peerId:alex.user.id},422);
const nomination=await alex.call('nominate_peer',{participantId:review.id,peerId:drew.user.id});
await alex.call('nominate_peer',{participantId:review.id,peerId:drew.user.id},422);
await jordan.call('decide_peer',{id:nomination.id,status:'approved'},404);
await casey.call('decide_peer',{id:nomination.id,status:'approved'});
await casey.call('decide_peer',{id:nomination.id,status:'approved'},409);
const peerRequests=(await drew.call('workspace&scope=employee')).data.requests.filter(r=>r.type==='peer'&&r.employee==='Alex Morgan');
assert.equal(peerRequests.length,1);assert.equal(peerRequests[0].canSubmit,true);
const form=await drew.call(`feedback_form&id=${peerRequests[0].id}`);
await drew.call('submit_personal_feedback',{id:peerRequests[0].id,ratings:form.competencies.map(c=>({competencyId:Number(c.id),score:4,comment:'Clear handover examples.'}))});
const rejection=await alex.call('nominate_peer',{participantId:review.id,peerId:blair.user.id});
await casey.call('decide_peer',{id:rejection.id,status:'rejected'});
assert(!(await blair.call('workspace&scope=employee')).data.requests.some(r=>r.employee==='Alex Morgan'&&r.cycle===review.cycle));
let team=await casey.call('dashboard');
const ready=team.employees.find(e=>e.name==='Jamie Vale');
assert.equal(ready.cycleStatus,'manager_review');
const ratings=team.competencies.map(c=>({competencyId:Number(c.id),score:4,comment:'Meets the agreed criteria.'}));
const submission={participantId:Number(ready.participantId),rating:4,summary:'Consistent delivery and clear ownership.',competencies:ratings};
await jordan.call('submit_review',submission,403);
await casey.call('submit_review',{...submission,rating:6},422);
await casey.call('submit_review',submission);
assert.equal((await casey.call('dashboard')).employees.find(e=>e.id===ready.id).reviewStatusCode,'manager_submitted');
assert.equal((await jamie.call('workspace&scope=employee')).data.reviews[0].final_rating,null);
await jamie.call(`peer_candidates&participantId=${ready.participantId}`,null,409);
const next='2099-01-31';
const goal=await casey.call('create_goal',{employeeId:alex.user.id,title:'Handoff practice',target:'Produce a clear example',due:next,steps:['Draft','Check']});
assert((await alex.call('workspace&scope=employee')).data.goals.some(g=>g.id===goal.id));
await jordan.call(`work_item&type=goal&id=${goal.id}`,null,404);
const pip=await casey.call('create_pip',{employeeId:alex.user.id,hrOwnerId:taylor.user.id,reason:'Practice the agreed process',start:'2099-01-01',end:next,objective:'Use the checklist',criteria:'Two checked examples',objectiveDue:'2099-01-20',steps:['Prepare','Practice']});
await casey.call('add_pip_objective',{pipId:pip.id,objective:'Review evidence',criteria:'One review',due:'2099-02-01',steps:['Review']},422);
await casey.call('add_pip_objective',{pipId:pip.id,objective:'Review evidence',criteria:'One review',due:'2099-01-25',steps:['Review']});
await casey.call('add_pip_checkin',{pipId:pip.id,date:'2099-01-10',notes:'Practice has begun.'});
await casey.call('update_pip_status',{id:pip.id,status:'extended',note:''},422);
await casey.call('update_pip_status',{id:pip.id,status:'extended',note:'Continue the agreed practice.'});
await casey.call('update_pip_status',{id:pip.id,status:'closed',note:'Demonstration complete.'});
await casey.call('add_pip_checkin',{pipId:pip.id,date:'2099-01-11',notes:'Too late'},409);
await casey.call('update_pip_status',{id:pip.id,status:'active',note:'Reopen'},409);
const path=(await alex.call(`org_path&employeeId=${alex.user.id}`)).path;
assert(path.length>=4);
await alex.call('org_change_manager',{employeeId:alex.user.id,managerId:jordan.user.id,effectiveFrom:'2099-01-01'},403);
await riley.call('org_change_manager',{employeeId:casey.user.id,managerId:alex.user.id,effectiveFrom:'2099-01-01'},422);
team=await casey.call('dashboard');
await casey.call('mark_notifications_read',{ids:team.notifications.map(n=>n.id)});
assert((await casey.call('dashboard')).notifications.every(n=>!n.unread));
await alex.call('change_password',{currentPassword:'wrong',newPassword:'Handoff12345',confirmPassword:'Handoff12345'},401);
await alex.call('change_password',{currentPassword:'password123',newPassword:'Handoff12345',confirmPassword:'Handoff12345'});
await alex.call('change_password',{currentPassword:'Handoff12345',newPassword:'Password12345',confirmPassword:'Password12345'});
await alex.call('logout',{});
await alex.call('me',null,401);
console.log('PASS: nomination/approval/form/submission, rejection, review submission/privacy, assigned goals, PIP lifecycle, hierarchy boundaries, notifications, password and logout.');
